on:
  push:
    branches:
    - main

name: CI

jobs:
  build_and_test:
    name: fakhrusy-com-admin
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm run buildcss
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked trunk
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - run: trunk build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./dist
          remote_path: ${{ secrets.SERVER_DEPLOY_PATH }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_PRIVATE_KEY_KEY }}